### PR TITLE
Remove deprecated tevkori_get_src_sizes

### PR DESCRIPTION
**Pull request by jaspermdegroot**
I think we can remove this by now.

### CODE REVIEW

**Comment by joemcgill** [comment]
Looks like we need to rebase this branch now. No worries if this doesn't get in this release, but we should merge it when it's ready.

**Comment by jaspermdegroot** [comment]
@joemcgill 

I just rebased this branch.

**Comment by joemcgill** [comment]
:+1:

**Comment by joemcgill** [comment]
We need to add this to the changelogs in readme.txt and readme.md in #180

**Pull request merged**
