### PR TITLE
Fixes for tevkori_get_srcset_array

### PR DESCRIPTION
**Pull request by orionrush**
Removes possible duplicates in array before returning tevkori_get_srcset_array. 
Also adds check for edge case where an image may not have metadata stored. 

Replaces PR: https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/107 & https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/109

### CODE REVIEW

**Comment by jaspermdegroot** [comment]
@orionrush 

Thanks for your PR. We would like to split this up. Do you mind creating a new PR for for each of the first two commits, using the my feedback from the comments on your commits? Let us know if you have any questions! Thanks!

**Comment by orionrush** [comment]
@jaspermdegroot

I'm afraid jasper that at this moment I'll not be able to pull this together in a timely way. It's a straightforward check so no ownership on my part. Go ahead and break it apart the PR as you see fit. 

Best,
Ben

**Comment by jaspermdegroot** [comment]
@orionrush 

Thanks for your reply. No problem, I will create those PRs. Thanks for you work on this!

**Comment by Wilto** [comment]
@jaspermdegroot: Thanks, man!

**Comment by jaspermdegroot** [comment]
Replaced by PRs #136 and #137

@joemcgill or @tevko - Can one of you close this PR?

**Comment by joemcgill** [comment]
Got it. Thanks!

**Pull request closed without merging**
