### PR TITLE
Smart resize

### PR DESCRIPTION
**Pull request by nwtn**
See #84

### CODE REVIEW

**Comment by joemcgill** [comment]
@nwtn looking at this again tonight, I think we should simply remove the last line:

```
add_filter('wp_image_editors', 'tevkori_wp_image_editors');
```

and people can add that line to their functions.php file in order to opt-in to the advanced compression settings. What do you think?

**Comment by peterwilsoncc** [comment]
To take the functions.php path, `add_theme_support( 'advanced-image-compression' )` is a better course, the hooked function becomes

	function tevkori_wp_image_editors( $editors ) {
		if ( current_theme_supports( 'advanced-image-compression' ) ) {
			array_unshift( $editors, 'WP_Image_Editor_Respimg' );
			return $editors;
		}
	}

**Comment by joemcgill** [comment]
@peterwilsoncc I like that move better, let's go that route.

**Comment by nwtn** [comment]
Done and done. README change suggestions?

**Pull request merged**
