### PR TITLE
For discussion: ImageMagick biz

### PR DESCRIPTION
**Pull request by nwtn**
See <http://ircbot.responsiveimages.org/bot/log/respimg/2015-04-20#T125175>.

Basically this will use a different set of ImageMagick commands than what WordPress uses by default for resizing images. In most cases it should produces files that look identical to resizing done with Photoshop’s “Save for Web”, but at smaller file sizes than either Photoshop or WordPress’s default options.

### CODE REVIEW

**Comment by jaspermdegroot** [comment]
I think this is outside the scope of this plugin. Would be a nice plugin on its own.

Shouldn't there be a check if ImageMagick is installed on the server?

**Comment by tevko** [comment]
I don't think this is out of scope.  The whole purpose of this plugin is to deliver a responsive image to the wordpress user. This pr does an excellent job of making sure that image is automatically resized with the best possible quality, in order to deliver the best resource to the end user

**Comment by nwtn** [comment]
> Shouldn't there be a check if ImageMagick is installed on the server?

There is in `WP_Image_Editor_Imagick`, which this extends. The check *should* get run automatically, and fallback to GD if it fails, but I don’t have an IMless install to check on ATM. I'd love if somebody could try that out.

**Comment by kadamwhite** [comment]
Since ImageMagick is used within WP's internals when available, I think it's definitely in-scope

**Comment by joemcgill** [comment]
Thanks @nwtn there's so much to love about this. I checked out the branch and ran a few tests on my end and am seeing huge size savings. In one case, as much as 60%. Really useful.

On the downside, I still have some performance concerns in terms of the CPU resources required to do the extra compression. In my dev environment, I attempted to regenerate thumbnails with this installed and it immediately pegged out the CPU. I think more tweaking may need to be done here.

I actually sort of lean toward the "out of scope" camp for this functionality but would love to see it in another plugin. If we do include this, I think we need to make it an opt-in feature—at least initially—that gets turned on via a checkbox on the media settings page or by setting an options flag in functions.php or something.

**Comment by kadamwhite** [comment]
...don't try to comment on a PR from your phone, lest you close it! Sorry. But yes, I think it is in scope for us to try to do the right thing here, and optimizing the images for size and quality feels like the right thing.

**Comment by joemcgill** [comment]
I would also add that the first place where I tried this out, ImageMagick was not installed, and image resizing worked like normal. So I think the checks currently in place are working ok.

**Comment by joemcgill** [comment]
After a lengthy discussion in WordPress Slack, the plan is to merge this into a dev branch (we'll keep master tracking the WordPress.org repo) and make it an opt-in feature that someone would enable through a filter in their functions.php or similar.

**Comment by jaspermdegroot** [comment]
Sounds good :+1

**Comment by nwtn** [comment]
closing, will re-open against dev branch

**Pull request closed without merging**
