### PR TITLE
Add Composer support.

### PR DESCRIPTION
**Pull request by ryanmarkel**
Add composer.json to support inclusion as a dependency.

Documentation: https://getcomposer.org/doc/02-libraries.md

### CODE REVIEW

**Comment by joemcgill** [comment]
@ryanmarkel I'm not an expert with Composer, but do we need to explicitly add the composer.json file if you were to use this: http://wpackagist.org/search?q=ricg-responsive-images&type=any&search=

**Comment by ryanmarkel** [comment]
It is not necessary, but in any case IMO it's a good idea to support it independently from Packagist. That way, developers using Composer have the option to install directly from the source repo.

**Comment by joemcgill** [comment]
Thanks @ryanmarkel. It makes sense to me and I don't see any downside here. Thanks for the PR. One last request – would you mind making the PR against our dev branch instead of master?

**Comment by ryanmarkel** [comment]
Can do. Closing this because I don't really understand how to "switch" my PR and (apparently?) I need to re-fork to avoid a needlessly dirty commit history.

**Pull request closed without merging**
