### PR TITLE
3.0 sync with core

### PR DESCRIPTION
**Pull request by jaspermdegroot**
This brings the new functions that we worked on for WordPress core to the plugin and deprecates all plugin core functions.
Since the new functions for WP core are still under development we have to update their code (and maybe the code in our deprecated core functions as well) before merging into dev. It can already be merged in our 3.0 WIP branch "199-post-merge-cleanup" though.

One thing to look into is ```tevkori_get_sizes``` where we used ```image_constrain_size_for_editor```. I like to test if this returns the same as the new WP core sizes function (```wp_get_attachment_image_sizes```) where we don't use this anymore.
We can test this with an image larger than ```$content_width``` and then adding/removing a filter to/from ```tevkori_image_sizes_args``` even if this filter doesn't do anything. The fact that it has a filter will make it use the old code while without filter it calls the new function.

### CODE REVIEW

**Comment by jaspermdegroot** [comment]
Still one failing test which I think have to do with what I already mentioned, ```image_constrain_size_for_editor()```. Will look into that.

**Comment by jaspermdegroot** [comment]
I can confirm that the failing sizes test has to do with ```image_constrain_size_for_editor()```.

In ```tevkori_get_sizes()``` we constrained all images to the content width. The test is based on that.
In the new function ```wp_get_attachment_image_sizes()``` we don't call  ```image_constrain_size_for_editor()```. When an image is inserted in the content it gets already constrained and the width value that is passed to the sizes function is the constrained width. Exception is when an image is inserted at full size. Post thumbnails are not constrained.

I think this is the correct behaviour so I suggest to update the test to reflect this. We still use the code of the old ```tevkori_get_sizes()``` function in case the ```$args``` param or the ```tevkori_image_sizes_args``` filter is used so we need to change that code to make it behave the same as the new function.

**Comment by tevko** [comment]
Makes sense. +1

**Comment by jaspermdegroot** [comment]
When I run the tests locally against an older WordPress version (tested 4.2) they all pass. So I don't understand why they still fail on Travis after 29d7fcb :(

**Pull request merged**
