### PR TITLE
Add srcset attribute to gallery images

### PR DESCRIPTION
**Pull request by jaspermdegroot**
Currently gallery images don't get a ```srcset``` attribute. By using the ```wp_get_attachment_image_attributes``` filter the ```srcset``` attribute will be added to both post thumbnails and gallery images.

Note: In the function that I replaced, either the comment (```data-sizes```) or the attribute name (```sizes``) in the code was wrong...
```
// Build the data-sizes attribute if sizes were returned.
if ( $sizes ) {
	$sizes = 'sizes="' . $sizes . '"';
}
```
Elsewhere in the code you use ```data-sizes``` so I guess the attribute name is wrong, but I don't understand why. I use ```data-sizes``` in my own code for the Lazysizes plugin, but Picturefill doesn't do anything with ```data-``` attributes, right? Anyway, I kept the mistake in the code. I can always rebase when it's fixed on master.

### CODE REVIEW

**Comment by joemcgill** [comment]
Thanks for the PR @jaspermdegroot. I'd be very happy to get srcset and sizes support on galleries.

A couple of things: first, the function `tevkori_get_srcset_string()` needs to return both the attribute and value, like `srcset="{{ whatever }}"` because it can also be used in a template tag like: 

```
<img src="/path/to/my-image.jpg" <?php echo tevkori_get_srcset_string( $id, $size ); ?> />
```

I'd be open to abstracting the internals of that into a new function called `tevkori_get_srcset()` or you can use `tevkori_get_srcset_array()` to get the sources and drop them into your filter. Either is fine.

Second, thanks for pointing out the docs inconsistency with 'sizes' vs 'data-sizes'. Since content images are actually embedded in posts (thus, saved to the database) we opted to use data-sizes, which get filtered to a `sizes` attribute on output in order to give us a little more flexibility going forward. Any images that are generated dynamically (e.g., post_thumbnails) are fine to get the sizes attribute applied. So the filter on 'the_content' should be using data-sizes while the other filter uses 'sizes'.

We'll also want to add some tests for this since `wp_get_attachement_image()` is used in a lot of other places in core.

Could you refresh your patch to fix the couple of issues I mentioned above re: `tevkori_get_srcset_string()` (and feel free to include that inline doc fix if you like for data-sizes). I can work up some tests unless you want to take a stab at them. Thanks!

**Comment by jaspermdegroot** [comment]
@joemcgill 

Thanks for your feedback.

> the function tevkori_get_srcset_string() needs to return both the attribute and value, like srcset="{{ whatever }}" because it can also be used in a template tag

Good point! I didn't think of that. I added a wrapper function.

> we opted to use data-sizes, which get filtered to a sizes attribute on output

Ah ok. I somehow overlooked the ```tevkori_filter_content_sizes``` function.
I fixed the inline doc

> I can work up some tests

That would be great!

Thanks!

**Comment by Schweinepriester** [comment]
great to see somebody already brought this up and even is working on it!
looking forward to be able to use this :)

**Comment by joemcgill** [comment]
Hey @jaspermdegroot, I'd like to add a check to the filter that sees if there is already a `sizes` key in the attributes array before running our sizes calculations. Same for srcset. This would keep us from accidentally overwriting those attributes if someone is passing them directly into the `wp_get_attachment_image()` function. So, something like:

```
if ( ! isset( $attr['sizes'] ) {
  $sizes = tevkori_get_sizes( $attachment_id, $size );
  // Build the sizes attribute if sizes were returned.
  if ( $sizes ) {
    $attr['sizes'] = $sizes;
  }
}
```

And the same pattern for srcset. With that, I think this is ready to go.

**Comment by jaspermdegroot** [comment]
@joemcgill 

Ok, I will implement those checks.
Should this PR be against the dev branch instead of master?

**Comment by joemcgill** [comment]
@jaspermdegroot, yes. If you could point this at dev, that would be great.

**Comment by jaspermdegroot** [comment]
Replaced by PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/92

**Pull request closed without merging**
